# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            dockerfile: Dockerfile
        working_dir: /var/www
        restart: unless-stopped
        ports:
            - 8080:80
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        depends_on:
            - mysql
        volumes:
            - ./:/var/www:cached
        networks:
            - lahmi

    mysql:
        image: 'mysql:5.6'
        ports:
            - '${DB_PORT}:3306'
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - lahmi

networks:
    lahmi:
        driver: bridge
volumes:
    dbdata:
        driver: local